name: Build ZMK Firmware

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: zmkfirmware/zmk-build-arm:stable
    name: Build ZMK Firmware
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: config

      - name: Cache West modules
        uses: actions/cache@v4
        with:
          path: |
            modules/
            tools/
            zephyr/
            bootloader/
            zmk/
          key: ${{ runner.os }}-build-${{ hashFiles('config/west.yml') }}
          restore-keys: |
            ${{ runner.os }}-build-

      - name: West Init
        run: west init -l config

      - name: West Update
        run: west update

      - name: West Zephyr Export
        run: west zephyr-export

      - name: Build firmware
        run: west build -s zmk/app -b nice_nano_v2 -- -DZMK_CONFIG="${GITHUB_WORKSPACE}/config" -DSHIELD=mkbd_macropad

      - name: Create firmware directory
        run: mkdir -p firmware

      - name: Copy firmware
        run: cp build/zephyr/zmk.uf2 firmware/mkbd_macropad_nice_nano_v2.uf2

      - name: Upload firmware
        uses: actions/upload-artifact@v4
        with:
          name: mkbd_macropad_firmware
          path: firmware/